### ISSUE TITLE
Script fails if 7 is used for Sunday instead of 0

### ISSUE THREAD

**Issue by gkankstech** [bradyholt/cRonstrue#4]
In most cron implementation it is valid to represent Sunday as 0 or 7.  For example 2-7 (for days of week) represents Tuesday through Sunday).

If an entry uses the 7 version of this syntax the script errors.

Using the execution engine I am using the error stack is this:

Javascript error: 
org.mozilla.javascript.JavaScriptException: TypeError: Cannot call method "replace" of undefined (script#5)
	at org.mozilla.javascript.gen.script_11._c_anonymous_11(script:5)
	at org.mozilla.javascript.gen.script_11.call(script)
	at org.mozilla.javascript.optimizer.OptRuntime.callProp0(OptRuntime.java:119)
	at org.mozilla.javascript.gen.script_11._c_anonymous_9(script:5)
	at org.mozilla.javascript.gen.script_11.call(script)
	at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:76)
	at org.mozilla.javascript.gen.script_11._c_script_0(script:11)
	at org.mozilla.javascript.gen.script_11.call(script)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:426)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3178)
	at org.mozilla.javascript.gen.script_11.call(script)
	at org.mozilla.javascript.gen.script_11.exec(script)

**Comment by bradyholt** [comment]
Thanks for the report. At least in the Quartz implementation, 7 always means Saturday (http://www.quartz-scheduler.org/documentation/quartz-2.x/tutorials/crontrigger.html).  There is already the `dayOfWeekStartIndexZero` option here: `https://github.com/bradyholt/cRonstrue/blob/master/src/options.ts#L4` which accounts for 1-7 (SUN-SAT) or 0-6 (SUN-SAT).  

So, a solution may be that if `dayOfWeekStartIndexZero === true` (the [default](https://github.com/bradyholt/cRonstrue/blob/master/src/expressionDescriptor.ts#L34)), we should interpret 7 as Sunday as well. If `dayOfWeekStartIndexZero === false`, 7 always means Saturday.

**Comment by bradyholt** [comment]
Fixe released to npm as 0.3.1: https://github.com/bradyholt/cRonstrue/releases/tag/v0.3.1
